spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/remittance_db
    username: remittance
    password: remittance
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

# 암호화 설정
security:
  encryption:
    key: wirebarleySecretKey1234567890wirebarleySecretKey1234

logging:
  level:
    root: INFO
    com.wirebarley: DEBUG
    org.hibernate.SQL: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
